package com.lin.dao.peotry;

import com.lin.entity.peotry.WordFinalBean;
import com.lin.entity.peotry.WordFinalBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordFinalBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    long countByExample(WordFinalBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int deleteByExample(WordFinalBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int insert(WordFinalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int insertSelective(WordFinalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    List<WordFinalBean> selectByExample(WordFinalBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    WordFinalBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") WordFinalBean record, @Param("example") WordFinalBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int updateByExample(@Param("record") WordFinalBean record, @Param("example") WordFinalBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int updateByPrimaryKeySelective(WordFinalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    int updateByPrimaryKey(WordFinalBean record);
}