package com.lin.entity.peotry;

import java.util.ArrayList;
import java.util.List;

public class WordFinalBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public WordFinalBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFinal_typeIsNull() {
            addCriterion("final_type is null");
            return (Criteria) this;
        }

        public Criteria andFinal_typeIsNotNull() {
            addCriterion("final_type is not null");
            return (Criteria) this;
        }

        public Criteria andFinal_typeEqualTo(Integer value) {
            addCriterion("final_type =", value, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeNotEqualTo(Integer value) {
            addCriterion("final_type <>", value, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeGreaterThan(Integer value) {
            addCriterion("final_type >", value, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("final_type >=", value, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeLessThan(Integer value) {
            addCriterion("final_type <", value, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeLessThanOrEqualTo(Integer value) {
            addCriterion("final_type <=", value, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeIn(List<Integer> values) {
            addCriterion("final_type in", values, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeNotIn(List<Integer> values) {
            addCriterion("final_type not in", values, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeBetween(Integer value1, Integer value2) {
            addCriterion("final_type between", value1, value2, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("final_type not between", value1, value2, "final_type");
            return (Criteria) this;
        }

        public Criteria andFinal_nameIsNull() {
            addCriterion("final_name is null");
            return (Criteria) this;
        }

        public Criteria andFinal_nameIsNotNull() {
            addCriterion("final_name is not null");
            return (Criteria) this;
        }

        public Criteria andFinal_nameEqualTo(String value) {
            addCriterion("final_name =", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameNotEqualTo(String value) {
            addCriterion("final_name <>", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameGreaterThan(String value) {
            addCriterion("final_name >", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameGreaterThanOrEqualTo(String value) {
            addCriterion("final_name >=", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameLessThan(String value) {
            addCriterion("final_name <", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameLessThanOrEqualTo(String value) {
            addCriterion("final_name <=", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameLike(String value) {
            addCriterion("final_name like", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameNotLike(String value) {
            addCriterion("final_name not like", value, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameIn(List<String> values) {
            addCriterion("final_name in", values, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameNotIn(List<String> values) {
            addCriterion("final_name not in", values, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameBetween(String value1, String value2) {
            addCriterion("final_name between", value1, value2, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_nameNotBetween(String value1, String value2) {
            addCriterion("final_name not between", value1, value2, "final_name");
            return (Criteria) this;
        }

        public Criteria andFinal_showIsNull() {
            addCriterion("final_show is null");
            return (Criteria) this;
        }

        public Criteria andFinal_showIsNotNull() {
            addCriterion("final_show is not null");
            return (Criteria) this;
        }

        public Criteria andFinal_showEqualTo(String value) {
            addCriterion("final_show =", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showNotEqualTo(String value) {
            addCriterion("final_show <>", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showGreaterThan(String value) {
            addCriterion("final_show >", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showGreaterThanOrEqualTo(String value) {
            addCriterion("final_show >=", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showLessThan(String value) {
            addCriterion("final_show <", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showLessThanOrEqualTo(String value) {
            addCriterion("final_show <=", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showLike(String value) {
            addCriterion("final_show like", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showNotLike(String value) {
            addCriterion("final_show not like", value, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showIn(List<String> values) {
            addCriterion("final_show in", values, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showNotIn(List<String> values) {
            addCriterion("final_show not in", values, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showBetween(String value1, String value2) {
            addCriterion("final_show between", value1, value2, "final_show");
            return (Criteria) this;
        }

        public Criteria andFinal_showNotBetween(String value1, String value2) {
            addCriterion("final_show not between", value1, value2, "final_show");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_final
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 05 16:55:49 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_final
     *
     * @mbg.generated Mon Feb 05 16:55:49 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}